Add Inherited Properties To Base Classes (18)
CenterEdge/Yardarm pull request #19
Opened 2021-02-19 20:22 UTC by mmmasent

Motivation
----
Yardarm fails to add properties from abstract/interfaces tags to child classes that reference them using the `allOf` schema tag

Modifications
----
* Adjusted `AllOfSchemaGenerator` to add interface/abstract class properties to the inheriting class

Result
----
All classes inheriting from another class using the `allOf` schema should now receive all the expected properties

2021-02-21 14:43 UTC, brantburnett commented
@mmmasent Can you point out an example schema that this change fixes please? I just want to make sure I fully understand. Thanks.

2021-02-21 15:33 UTC, mmmasent commented
@brantburnett This fixes an issue where the properties from the base class/interface are not present on the child class. As a simple example, you can look at the new json inheritance spec I added to help find this issue and the other issue related to nested inheritance. But for a quick glance:

`IMembershipDuration` is the abstract class `MembershipDuration`. That class has a property for the enum value of its type and a new Fake doubly nested type I created to validate the issue with one of/all of nested inheritance.

Below is what Yardarm currently generates; despite the all of tag being present, the property does not exist on the child class. The interface that is generated also does not have the property.

![image](https://user-images.githubusercontent.com/29384916/108629324-4b438a80-742d-11eb-8524-dac8c8489700.png)

With this update, base class properties will be present and available to use in consuming clients:
![image](https://user-images.githubusercontent.com/29384916/108629820-ba21e300-742f-11eb-9f63-e2ddb34fdfd5.png)

2021-02-21 15:56 UTC, brantburnett commented
@mmmasent Thanks for the info, but I'm also interested in the source OpenAPI spec. I want to see the logical spec that's causing this situation in C#. Thanks.

2021-02-28 14:21 UTC, brantburnett requested changes
@mmmasent 

I've reviewed this, and I think it has some design flaws. It does account for one scenario, but it does so by breaking another scenario. Basically, you have stumbled across a more advanced scenario that needs a more advanced design.

The current implementation of AllOf is designed to handle base classes, not interfaces. This is why it doesn't implement the properties. If you look at `FakeImplementationA` from your example file, you'll note that this change causes it to shadow all of the properties from AFakeAbstract with new implementations. This will break polymorphism.

Your case is a more advanced case where the model being referenced via `allOf` has a discriminator. As such, the model itself is just an interface, each version of the discriminator has the concrete implementation.

Frankly, I'm not even convinced that the example model is correct OpenAPI 3 usage. It may be, but I've never done it this way. In schemas I have written, the allOf shouldn't go back up and include the base discriminator which includes it. It's creating a circular reference in the schema. Normally, if I have common fields I want on all versions, I make that a completely separate schema for the shared fields. You can see an example of this in `centeredge-cardsystem.yaml` if you look at `CardTransaction` (the discriminator) and `TransactionBase` (the shared properties).

2021-02-28 14:21 UTC, brantburnett commented on src/Yardarm.CommandLine/inheritanceOnlyTestSpec.json
> +{
I'd prefer it if a simple example of the use case were adding to the existing yaml file, rather than adding a whole additional schema file.

2024-04-24 17:08 UTC, mmmasent commented
This PR is ancient and should not longer remain in a state of perpetual freeze

2024-04-24 17:08 UTC, closed without merging